# Generated by Django 3.1.3 on 2020-11-20 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmsUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address_line_1', models.CharField(max_length=255, null=True)),
                ('address_line_2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('profile_picture', models.TextField(null=True)),
                ('belongs_to_ams_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ams_user_profiles',
            },
        ),
    ]
