# Generated by Django 3.1.3 on 2020-11-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amsuserprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='amsuserprofile',
            table='user_profiles',
        ),
    ]
