# Generated by Django 3.1.3 on 2020-11-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_auto_20201120_1001'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amsuserprofile',
            table='ams_user_profiles',
        ),
    ]
