# Generated by Django 3.1.3 on 2020-11-20 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ams', '0003_auto_20201120_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ams_logs',
            },
        ),
        migrations.CreateModel(
            name='AmsCompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('pan', models.CharField(max_length=20, null=True)),
                ('gstin', models.CharField(max_length=30, null=True)),
                ('registration_number', models.CharField(max_length=100, null=True)),
                ('phone_number_1', models.CharField(max_length=15, null=True)),
                ('phone_number_2', models.CharField(max_length=15, null=True)),
                ('business_email_1', models.EmailField(max_length=100, null=True)),
                ('business_email_2', models.EmailField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('address_line_1', models.CharField(max_length=255, null=True)),
                ('address_line_2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('logo', models.TextField(null=True)),
                ('is_branch', models.BooleanField(default=False)),
                ('belongs_to_ams_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ams_company_profiles',
            },
        ),
    ]
